### ISSUE TITLE
Provide view option for a compact list

### ISSUE THREAD

**Issue by geoffm** [Solution-locale/solutionlocale.ca#22]
Ideally, the list would be sortable.

**Comment by jpmurray** [comment]
Definitely. It's also a step to offer printable list, which is something we've been asked for also.

**Comment by geoffm** [comment]
Great improvement. If I may add some more suggestions:

- [ ] Business name could be a hyperlink to the business' profile
- [ ] Displaying the full address doesn't seem that important. I think just the town would be sufficient. Full address could be displayed as a tooltip. Town could be a hyperlink to google maps.
- [ ] Category column: Would be useful to see what categories the business is at a glance. If you find words take too much space, icons could be used. If you want to implement this I can suggest icons from public libraries like font-awesome, if that is any help. Tooltips could be used to make things clear.
- [ ] Delivery options would also be a useful column.
- [ ] The column Action could have two icons with hyperlinks: www and mail. "Voir" wouldn't be relevant if first suggestion above is applied.
- [ ] 12px padding for td and table is too much. Just removing the padding property altogether seems just right (0px). Makes for faster reading and less scrolling. See screenshot.
![2020-03-31 20_19_13-Solution Locale](https://user-images.githubusercontent.com/901518/78087507-531abc00-738f-11ea-81e3-3b60a641612e.png)

**Comment by jpmurray** [comment]
To answer some of them:

- Most of your (good!) suggestions aren't _right now_ addressed because the original request from some of our partners was to have printable list of local business, so that can explain why some information is there, other are not, and why we choose to display those specifically (I'm thinking about the full address for example!).
- About Iicons: we're on it it's not coming tomorrow, but icons are in the pipeline, if only for the map to differenciate between business styles.
- I'm going to say that a category column is overkill, since someone could always sort by categories using the always available buttons at the top of the page. Seems to go against the idea of having a compact view too,  to be honest.
- Specifically about the padding, I'm going to tag @poliquinp and ask if your frontend guy has an opinion on this? ;-)
- For links on business name: *good catch*. Link is there in source, but something is messing with it. This is corrected and will be deployed in the next update!

Now I'm going to close this as issue is finished, but we can still continue discussin on the matter!
